baseURL = 'http://mumble-memo.site/'
languageCode = 'en-us'
title = 'My New Hugo Site'
theme = "terminal"

[params]
  contentTypeName = "posts"
  themeColor = "orange"
  showMenuItems = 5
  fullWidthTheme = false
  centerTheme = true

[languages]
  [languages.en]
    title = "Mumble-memo"
    subtitle = "A simple, retro theme for Hugo"
    keywords = ""
    copyright = ""
    menuMore = "Show more"
    readMore = "Read more"
    readOtherPosts = "Read other posts"

    [languages.en.params.logo]
      logoText = "LIN"
      logoHomeLink = "/"

    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "posts"
        name = "Posts"
        url = "/posts"
        weight = -3
      [[languages.en.menu.main]]
        identifier = "about"
        name = "About"
        url = "/about"
        weight = -2
      [[languages.en.menu.main]]
        identifier = "tag"
        name = "Tags"
        url = "/tags"
        weight = -1